### ISSUE TITLE
You can upload the same file multiple times, and get different URLs every time

### ISSUE THREAD

**Issue by ifonefox** [oohnoitz/jii#14]
I uploaded a small file 3 times, and instead of getting the same URL every time, they are different ones. Does this mean that it is saving it every time? I'm not sure if this is a feature or a bug.

https://jii.moe/4k4o_jWo.txt
https://jii.moe/VyWsus-s.txt
https://jii.moe/N1FW_obo.txt

**Comment by oohnoitz** [comment]
Yes. Since the original scope of this project was to fulfill my own personal needs, it wasn't necessary for me to deal with data de-duplication. So I wouldn't really say that this is a feature or a bug at all. If there is a high demand for this to be implemented, I might consider tagging this as a feature request and work on it if time permits.

**Comment by oohnoitz** [comment]
@ifonefox After looking at your question again, I might have misunderstood what you were asking about.

Yes, it would be consider a feature. Each URL generated contains additional metadata about the file it is associated with, such as its original file name, size, MIME type, date modified, and etc. The metadata is then used to send additional data in the headers with the file which allows the client/user to download the file with its original file name instead of the GUID generated.

My previous comment still applies to an extent, but I hope that this answers your question.
